# Generated by Django 4.1.3 on 2022-11-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenCompare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reference_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Légumes', 'Vegetables'), ('Féculents', 'Starch'), ('Viande', 'Meat'), ('Boissons', 'Drinks'), ('Autres aliments', 'Elsefood'), ('Autres', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='eco_score',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
