# Generated by Django 4.1.3 on 2022-12-05 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GreenCompare', '0002_remove_user_reference_product_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Légumes', 'Vegetables'), ('Féculents', 'Starch'), ('Viande', 'Meat'), ('Boissons', 'Drinks'), ('Autres aliments', 'Elsefood'), ('Autres', 'Others')], max_length=100),
        ),
    ]
