# Generated by Django 4.1.3 on 2022-12-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenCompare', '0003_userlocation_delete_user_remove_product_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='reference_shop',
        ),
    ]
