# Generated by Django 4.1.2 on 2022-11-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('productor_name', models.CharField(default='No data for the productor name', max_length=200)),
                ('entitled', models.CharField(max_length=200)),
                ('category', models.CharField(default='No category', max_length=100)),
                ('eco_score', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncli', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=1000)),
                ('email', models.CharField(default='No email', max_length=200)),
                ('number', models.IntegerField(default=0)),
                ('reference_product', models.ManyToManyField(to='polls.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_shop', models.CharField(max_length=200)),
                ('shop_name', models.CharField(max_length=1000)),
                ('localisation', models.CharField(max_length=1000)),
                ('category', models.CharField(default='No category', max_length=1000)),
                ('description', models.CharField(default='No description', max_length=1000)),
                ('opening', models.BooleanField()),
                ('reference_product', models.ManyToManyField(to='polls.product')),
            ],
        ),
    ]
